START TRANSACTION;

CREATE TABLE IF NOT EXISTS shardT (
	stud_id_low INTEGER PRIMARY KEY,
	shard_id TEXT NOT NULL,
	shard_size INTEGER NOT NULL,
	valid_at INTEGER NOT NULL DEFAULT 0
);

COMMIT TRANSACTION;
